name: python 3.6
dependencies:
  - python=3.6
  - pip:
    - scikit-learn==0.20.1
    - numpy==1.15.4
    - matplotlib==3.0.1
    - tensorflow==1.12.0
    - keras==2.2.4
    - pandas==0.23.4
    - obspy==1.1.0